apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    run: {{ .Values.service.name }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.container.accountsPort }}
    protocol: {{ .Values.container.protocol }}
  selector:
    app: {{ .Values.accountsImage.name }}
