apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.volume.claimName }}
  labels:
    app: mongopv
spec:
  accessModes:
    - {{ .Values.volume.accessModes }}
  storageClassName: {{ .Values.volume.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.volume.storage }}
