# apiVersion: v1
# kind: Service
# metadata:
#   name: {{ include "accountshelm.fullname" . }}
#   labels:
#     app.kubernetes.io/name: {{ include "accountshelm.name" . }}
#     helm.sh/chart: {{ include "accountshelm.chart" . }}
#     app.kubernetes.io/instance: {{ .Release.Name }}
#     app.kubernetes.io/managed-by: {{ .Release.Service }}
# spec:
#   type: {{ .Values.service.type }}
#   ports:
#     - port: {{ .Values.service.port }}
#       targetPort: http
#       protocol: TCP
#       name: http
#   selector:
#     app.kubernetes.io/name: {{ include "accountshelm.name" . }}
#     app.kubernetes.io/instance: {{ .Release.Name }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
spec:
  ports:
  - port: {{ .Values.container.port }}
    protocol: {{ .Values.container.protocol }}
  selector:
    appdb: {{ .Values.appName }}
